name: Continuous Integration
on:
  push:
    branches:
      - "main"
      - "release/*"
    paths-ignore:
    - 'docs/**'
  pull_request:
    paths-ignore:
    - 'docs/**'
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [debug, release]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v2.1.0
      - name: Try get cached dependencies
        uses: actions/cache@v3.0.8
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Validate dependencies
        run: dotnet restore --locked-mode --packages ${{ github.workspace }}/.nuget/packages
      - name: Build
        run: dotnet msbuild -p:Configuration=${{ matrix.configuration }} -graph -isolate -bl:artifacts/log/build.binlog
      - name: Upload Results
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ matrix.os }}_${{ matrix.configuration }}
          path: |
            ./artifacts/bin/**/*
            ./artifacts/log/**/*
          if-no-files-found: error